### ISSUE TITLE
dangerous use of abs with float

### ISSUE THREAD

**Issue by delaere** [cp3-llbb/ZAAnalysis#3]
see: 
https://github.com/cp3-llbb/ZAAnalysis/blob/master/plugins/ZASimpleAnalyser.cc#L23

This is dangerous:
std::abs(float) -> float
abs(float) -> int

better use fabs or explicit std::abs .

**Comment by AlexandreMertens** [comment]
Thanks for checking the code!
Yes, I already saw it and yet didn't implemented in the previous PR.
I am doing the correction now.
